[features]
seeds = false
skip-lint = false
[programs.localnet]
orca_farm_controller = "8AFYzgM2eostiQwAgUM6BZwqED53UDDZTYikDhL8sZh4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/yugure/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
